#!/bin/bash

temp=$(getopt --name 'desk' --options 'h' --long 'help' -- "$@")
session='Desktop'

eval set -- "$temp"
unset temp

main() {
   # Parse command options
   parse_options $@

   create_session "$session"

   local panes=$(tmux list-panes -a)
   local pane_2="$(echo $panes | grep 'Desktop:1.2')"
   local pane_3="$(echo $panes | grep 'Desktop:1.3')"

   [ -z "$pane_2" ] && tmux split-window -h
   [ -z "$pane_3" ] && tmux split-window -d -l 10 -t 'Desktop:1.2' cava

   attach_session "$session"
}

attach_session() {
   local target="$1"

   # Attach if outside of tmux, switch if you're in tmux
   if [ -z "$TMUX" ]; then   
      tmux attach-session -t $target
   else
      tmux switch-client -t $target
   fi
}

create_session() {
   local target="$1"

   # Check if the session exists
   tmux has-session -t $target 2> /dev/null

   # Create the session if it doesn't exists
   # $? is the exit status of the previous command
   if [ $? != 0 ]; then
      # Get the hight and width of the terminal
      local lines="$(tput lines)"
      local columns="$(tput cols)"

      # Create a new session in detached mode
      TMUX='' tmux new-session -d -x "$columns" -y "$lines" -s "$target"
   fi
}

help() {
   echo 'Help Menu'
   exit 0
}

parse_options() {
   while [ -n "$1" ]; do
      case "$1" in
         '-h'|'--help')
            help
            break;;
         '--')
            shift
            break;;
         *)
			   echo 'Internal error!' >&2
			   exit 1;;
      esac
   done
}

main "$@"
