#!/bin/bash

command_dir="${0%/*}/_dotfiles"
config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/dotfiles"

temp=$(getopt --name 'dotfiles' --options 'hn' --long 'help,dry-run' -- "$@")

eval set -- "$temp"
unset temp

main() {
   options=()
   args=()

   parse_options "$@"

   local command="${args[0]}"
   unset args[0]

   case "$command" in
      'load'|'save')
         eval "$command_dir/$command ${options[@]} ${args[@]}";;
      *)
         help;;
   esac
}

help() {
   local text="\
      Usage: dotfiles [OPTION]...
      Manage the storage and repository of custom linux dotfiles.

      Mandatory arguments to long options are mandatory for short options too.
        -h, --help                 display this help and exit
        -n, --dry-run              perform a trial run with no changes made

      Exit status:
       0  if OK,
       1  if minor problems (e.g., cannot access subdirectory),
       2  if serious trouble (e.g., cannot access command-line argument)."

   echo "$text" | sed 's/^\s\{6\}//g'
   exit 0
}

parse_options() {
   while [ -n "$1" ]; do
      case "$1" in
         '-h'|'--help')   
            options+=(--help)
            shift && continue;;
         '-n'|'--dry-run')
            options+=(--dry-run)
            shift && continue;;
         '--')
            shift && break;;
         *)
			   echo 'Internal error!' >&2
			   exit 1;;
      esac
   done

   for arg; do
	   args+=("$arg")
   done
}

main "$@"