#!/bin/bash

# https://wttr.in/:help

if [[ -z "$WTTR_LOCATION" ]]; then
   WTTR_LOCATION=$(curl -s https://whatismycountry.com | grep -o '\(-\)\?[0-9]\+\.[0-9]\+&#176;, \(-\)\?[0-9]\+\.[0-9]\+&#176;' | sed 's/&#176;//g;s/ //')

   export WTTR_LOCATION
fi

if [[ -z "$WTTR_PARAMS" ]]; then
   WTTR_PARAMS='FQu'

   if [[ -t 1 ]] && [[ "$(tput cols)" -lt 125 ]]; then
      WTTR_PARAMS+='n'
   fi 2> /dev/null
fi

main() {
   local args=""

   for p in $WTTR_PARAMS "$@"; do
      args+=" --data-urlencode $p "
   done

  curl -fGsS -H "Accept-Language: ${LANG%_*}" $args --compressed "wttr.in/${WTTR_LOCATION}"
}

main "$@"
